version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bank_postgres
    environment:
      - POSTGRES_DB=bank_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=randomcode
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bank-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: bank_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@bank.com
      - PGADMIN_DEFAULT_PASSWORD=randomcode
    ports:
      - "5050:80"
    networks:
      - bank-network
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  bank-network:
    driver: bridge